import './globals.css';
import { Raleway } from '@next/font/google';

const font = Raleway({
  subsets: [`latin`], 
  preload: true, 
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preload" as="style" href={font.preload} />
        <style dangerouslySetInnerHTML={{ __html: font.styles }} />
      </head>
      <body className={font.className}>{children}</body>
    </html>
  );
}
